#!/usr/bin/env python3
"""Reconstruct phase cubes from saved vortex fitting parameters.

This script reads `*_vortex_results.pkl` generated by
`run_brainmodel_batch2.py`, selects sigma parameters per frame using
`last`, `best`, or a fixed `iteration`, and saves one reconstructed
phase cube per bundle.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm


THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[2]
PYBRAINMODEL_DIR = PROJECT_ROOT / "brainmodel" / "pybrainmodel"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(PYBRAINMODEL_DIR) not in sys.path:
    sys.path.insert(0, str(PYBRAINMODEL_DIR))

try:
    # Preferred import path for IDE/static analysis when workspace root is on sys.path.
    from brainmodel.pybrainmodel.vortex_model_gpu import VortexPhaseModel  # type: ignore
except ModuleNotFoundError:
    from vortex_model_gpu import VortexPhaseModel  # noqa: E402


BundleKey = Tuple[str, str, int, str]


def parse_bundle_name(bundle_name: str) -> Tuple[str, str, str, int]:
    """Parse bundle_name -> (drug, group, hemisphere, subject_num)."""
    last_part = bundle_name.split("_")[-1]
    hemisphere = last_part[-1]
    code = last_part[:-1]
    drug = code[:3]
    group = code[3:6]
    subject_num = int(code[6:])
    return drug, group, hemisphere, subject_num


def build_bundle_index(detect_root: Path) -> Dict[BundleKey, str]:
    """Map (drug, group, subject, hemisphere) to bundle_name."""
    index: Dict[BundleKey, str] = {}
    if not detect_root.exists():
        return index

    for drug_dir in sorted([p for p in detect_root.iterdir() if p.is_dir()]):
        for bundle_dir in sorted([p for p in drug_dir.iterdir() if p.is_dir()]):
            phase_path = bundle_dir / "phase_cube.npy"
            if not phase_path.exists():
                continue
            bundle_name = bundle_dir.name
            drug, group, hemisphere, subject = parse_bundle_name(bundle_name)
            key = (drug, group, subject, hemisphere)
            index[key] = bundle_name
    return index


def as_centroids(value) -> np.ndarray:
    arr = np.asarray(value)
    if arr.size == 0:
        return np.empty((0, 2), dtype=np.float32)
    arr = np.asarray(arr, dtype=np.float32)
    return arr.reshape(-1, 2)


def as_vector(value) -> np.ndarray:
    arr = np.asarray(value)
    if arr.size == 0:
        return np.empty((0,), dtype=np.float32)
    return np.asarray(arr, dtype=np.float32).reshape(-1)


def choose_iteration_index(cost_history: np.ndarray, mode: str, iteration: Optional[int]) -> int:
    if cost_history.size == 0:
        return -1
    if mode == "last":
        return int(cost_history.size - 1)
    if mode == "best":
        return int(np.argmin(cost_history))
    if mode == "iteration":
        if iteration is None:
            raise ValueError("mode=iteration requires --iteration")
        if iteration < 0 or iteration >= int(cost_history.size):
            raise ValueError(
                f"iteration={iteration} out of range [0, {int(cost_history.size) - 1}]"
            )
        return int(iteration)
    raise ValueError(f"Unknown mode: {mode}")


def reconstruct_frame(
    row: pd.Series,
    mask: np.ndarray,
    h: int,
    w: int,
    mode: str,
    iteration: Optional[int],
    device: str,
) -> np.ndarray:
    centroids_pos = as_centroids(row["centroids_pos"])
    centroids_neg = as_centroids(row["centroids_neg"])
    omega_pos = as_vector(row["omega_pos"])
    omega_neg = as_vector(row["omega_neg"])

    if centroids_pos.shape[0] + centroids_neg.shape[0] == 0:
        return np.full((h, w), np.nan, dtype=np.float32)

    cost_history = as_vector(row["cost_history"])
    if cost_history.size == 0:
        return np.full((h, w), np.nan, dtype=np.float32)

    sigma_pos_hist = np.asarray(row["sigmas_pos"])
    sigma_neg_hist = np.asarray(row["sigmas_neg"])
    selected_idx = choose_iteration_index(cost_history, mode, iteration)

    model = VortexPhaseModel(
        height=h,
        width=w,
        centroids_pos=centroids_pos,
        centroids_neg=centroids_neg,
        omega_pos=omega_pos,
        omega_neg=omega_neg,
        mask=mask,
        device=device,
    )

    with torch.no_grad():
        if model.n_pos > 0 and sigma_pos_hist.size > 0:
            sigma_pos = np.asarray(
                sigma_pos_hist[selected_idx], dtype=np.float32).reshape(-1)
            model.sigma_pos.data = torch.tensor(
                sigma_pos, dtype=torch.float32, device=device)
        if model.n_neg > 0 and sigma_neg_hist.size > 0:
            sigma_neg = np.asarray(
                sigma_neg_hist[selected_idx], dtype=np.float32).reshape(-1)
            model.sigma_neg.data = torch.tensor(
                sigma_neg, dtype=torch.float32, device=device)
        recon = model().detach().cpu().numpy().astype(np.float32, copy=False)

    return recon


def reconstruct_bundle(
    df_bundle: pd.DataFrame,
    bundle_name: str,
    phase_cube_path: Path,
    out_path: Path,
    mode: str,
    iteration: Optional[int],
    device: str,
    overwrite: bool,
) -> bool:
    if out_path.exists() and not overwrite:
        return False

    phase_cube = np.load(phase_cube_path)
    h, w, t = phase_cube.shape
    mask = ~np.isnan(phase_cube[:, :, 0])
    recon_cube = np.full((h, w, t), np.nan, dtype=np.float32)

    rows_by_frame = {int(row["frame"]): row for _, row in df_bundle.iterrows()}
    for frame in tqdm(
        range(t),
        desc=f"Frames {bundle_name}",
        leave=False,
    ):
        row = rows_by_frame.get(frame)
        if row is None:
            continue
        recon_cube[:, :, frame] = reconstruct_frame(
            row=row,
            mask=mask,
            h=h,
            w=w,
            mode=mode,
            iteration=iteration,
            device=device,
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.save(out_path, recon_cube)
    return True


def reconstruct_single_test_frame(
    *,
    detect_root: Path,
    results_pkl_paths: List[Path],
    mode: str,
    iteration: Optional[int],
    device: str,
    test_drug: str,
    test_group: str,
    test_hemi: str,
    test_subject: int,
    test_frame: int,
    test_output: Path,
) -> Path:
    existing_pkls = [p for p in results_pkl_paths if p.exists()]
    if not existing_pkls:
        raise FileNotFoundError("No valid --results-pkl files found.")

    pkl_path = None
    for p in existing_pkls:
        if p.stem.replace("_vortex_results", "") == test_drug:
            pkl_path = p
            break
    if pkl_path is None:
        pkl_path = existing_pkls[0]

    df = pd.read_pickle(pkl_path)
    if df.empty:
        raise ValueError(f"Empty results file: {pkl_path}")

    select = (
        (df["drug"] == test_drug)
        & (df["group"] == test_group)
        & (df["hemisphere"] == test_hemi)
        & (df["subject"] == test_subject)
        & (df["frame"] == test_frame)
    )
    rows = df.loc[select]
    if rows.empty:
        raise ValueError(
            "No matching row for "
            f"drug={test_drug}, group={test_group}, hemi={test_hemi}, "
            f"subject={test_subject}, frame={test_frame}"
        )
    row = rows.iloc[0]

    bundle_index = build_bundle_index(detect_root)
    key = (test_drug, test_group, test_subject, test_hemi)
    bundle_name = bundle_index.get(key)
    if bundle_name is None:
        raise ValueError(f"Could not map to bundle_name for key={key}")

    phase_cube_path = detect_root / test_drug / bundle_name / "phase_cube.npy"
    if not phase_cube_path.exists():
        raise FileNotFoundError(f"Missing phase cube: {phase_cube_path}")

    phase_cube = np.load(phase_cube_path)
    h, w, t = phase_cube.shape
    if test_frame < 0 or test_frame >= t:
        raise ValueError(f"test_frame={test_frame} out of range [0, {t - 1}]")
    mask = ~np.isnan(phase_cube[:, :, 0])

    recon = reconstruct_frame(
        row=row,
        mask=mask,
        h=h,
        w=w,
        mode=mode,
        iteration=iteration,
        device=device,
    )
    test_output.parent.mkdir(parents=True, exist_ok=True)
    np.save(test_output, recon.astype(np.float32, copy=False))
    print(
        f"Saved test frame to {test_output} "
        f"(bundle={bundle_name}, frame={test_frame}, mode={mode})"
    )
    return test_output


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Reconstruct phase cube from saved sigma histories.")
    parser.add_argument(
        "--mode",
        choices=["last", "best", "iteration"],
        default="best",
        help="How to select sigma from cost_history for each frame.",
    )
    parser.add_argument(
        "--iteration",
        type=int,
        default=None,
        help="0-based iteration index used when --mode iteration.",
    )
    parser.add_argument(
        "--device",
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Torch device, e.g. cuda or cpu.",
    )
    parser.add_argument(
        "--detect-root",
        type=Path,
        default=PROJECT_ROOT / "detect_results",
        help="Path to detect_results root.",
    )
    parser.add_argument(
        "--results-pkl",
        type=Path,
        nargs="+",
        required=True,
        help="Direct path(s) to *_vortex_results.pkl.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=PROJECT_ROOT / "brainmodel" / "results" / "phase_recon",
        help="Output directory for reconstructed phase cubes.",
    )
    parser.add_argument(
        "--drug",
        nargs="*",
        default=None,
        help="Optional drug filter, e.g. --drug DMT LSD.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files.",
    )
    parser.add_argument(
        "--test-mode",
        action="store_true",
        help="Reconstruct only one specified frame and save to --test-output.",
    )
    parser.add_argument("--test-drug", type=str, default=None,
                        help="Test target drug, e.g. DMT.")
    parser.add_argument("--test-group", type=str, default=None,
                        help="Test target group, e.g. DMT or PCB.")
    parser.add_argument("--test-hemi", type=str, default=None,
                        help="Test target hemisphere, e.g. L or R.")
    parser.add_argument("--test-subject", type=int,
                        default=None, help="Test target subject id.")
    parser.add_argument("--test-frame", type=int, default=None,
                        help="Test target frame index (0-based).")
    parser.add_argument(
        "--test-output",
        type=Path,
        default=Path("test.npy"),
        help="Output npy path in --test-mode.",
    )
    args = parser.parse_args()

    if args.test_mode:
        required = {
            "test_drug": args.test_drug,
            "test_group": args.test_group,
            "test_hemi": args.test_hemi,
            "test_subject": args.test_subject,
            "test_frame": args.test_frame,
        }
        missing = [k for k, v in required.items() if v is None]
        if missing:
            raise ValueError(f"--test-mode missing required args: {missing}")
        reconstruct_single_test_frame(
            detect_root=args.detect_root,
            results_pkl_paths=list(args.results_pkl),
            mode=args.mode,
            iteration=args.iteration,
            device=args.device,
            test_drug=str(args.test_drug),
            test_group=str(args.test_group),
            test_hemi=str(args.test_hemi),
            test_subject=int(args.test_subject),
            test_frame=int(args.test_frame),
            test_output=args.test_output,
        )
        return

    bundle_index = build_bundle_index(args.detect_root)
    if not bundle_index:
        raise FileNotFoundError(
            f"No bundles found under detect root: {args.detect_root}")

    pkl_files = sorted([p for p in args.results_pkl if p.exists()])
    if args.drug:
        allowed = set(args.drug)
        pkl_files = [p for p in pkl_files if p.stem.replace(
            "_vortex_results", "") in allowed]
    if not pkl_files:
        raise FileNotFoundError(
            "No valid result pickle files from --results-pkl.")

    total_saved = 0
    total_skipped = 0
    total_missing = 0

    for pkl_path in pkl_files:
        drug_name = pkl_path.stem.replace("_vortex_results", "")
        df = pd.read_pickle(pkl_path)
        if df.empty:
            continue

        required_cols = {
            "drug",
            "group",
            "subject",
            "hemisphere",
            "frame",
            "centroids_pos",
            "centroids_neg",
            "sigmas_pos",
            "sigmas_neg",
            "omega_pos",
            "omega_neg",
            "cost_history",
        }
        missing_cols = required_cols - set(df.columns)
        if missing_cols:
            raise KeyError(
                f"{pkl_path} missing columns: {sorted(missing_cols)}")

        group_cols = ["drug", "group", "subject", "hemisphere"]
        grouped = df.groupby(group_cols, sort=True)

        for (drug, group, subject, hemisphere), df_bundle in tqdm(
            grouped,
            desc=f"Reconstructing {drug_name}",
            leave=False,
        ):
            key = (drug, group, int(subject), hemisphere)
            bundle_name = bundle_index.get(key)
            if bundle_name is None:
                total_missing += 1
                print(f"[WARN] Missing bundle_name for key={key}")
                continue

            phase_cube_path = args.detect_root / drug / bundle_name / "phase_cube.npy"
            if not phase_cube_path.exists():
                total_missing += 1
                print(f"[WARN] Missing phase_cube.npy: {phase_cube_path}")
                continue

            out_name = f"phase_cube_recon_{bundle_name}.npy"
            out_path = args.output_root / drug / out_name

            df_bundle = df_bundle.sort_values("frame")
            print("using device={device}")
            saved = reconstruct_bundle(
                df_bundle=df_bundle,
                bundle_name=bundle_name,
                phase_cube_path=phase_cube_path,
                out_path=out_path,
                mode=args.mode,
                iteration=args.iteration,
                device=args.device,
                overwrite=args.overwrite,
            )
            if saved:
                total_saved += 1
            else:
                total_skipped += 1
                print(f"[SKIP] Output exists: {out_path}")

    print("Done.")
    print(f"Saved:   {total_saved}")
    print(f"Skipped: {total_skipped}")
    print(f"Missing: {total_missing}")


if __name__ == "__main__":
    main()
