#!/usr/bin/env python
"""
Group analysis for per-pattern MSD beta outputs.

The input is per_pattern_msd_beta.csv from scripts/pattern_msd_beta.py. The
script aggregates beta to subject/hemisphere level, then writes paired t-tests,
two-way repeated-measures ANOVA, and paired violin plots.

Example:
    python analysis/pattern_msd_beta_group.py ^
        --per-pattern analysis_outputs/pattern_msd_beta/dmt/per_pattern_msd_beta.csv ^
        --group-drug DMT ^
        --group-pcb PCB ^
        --out-dir analysis_outputs/pattern_msd_beta/dmt_group
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from analysis.all_metrics.config import Config
from analysis.all_metrics.utils import build_group_summary_df, plot_paired_violin, write_table


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Group statistics for MSD beta.")
    parser.add_argument(
        "--per-pattern",
        required=True,
        type=Path,
        help="per_pattern_msd_beta.csv generated by scripts/pattern_msd_beta.py.",
    )
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--group-drug", default="DMT")
    parser.add_argument("--group-pcb", default="PCB")
    parser.add_argument(
        "--metric",
        default="msd_beta",
        help="Per-pattern metric to aggregate. Default: msd_beta.",
    )
    parser.add_argument(
        "--subject-agg",
        choices=["mean", "median"],
        default="mean",
        help="How to aggregate pattern beta within each subject/hemisphere. Default: mean.",
    )
    parser.add_argument(
        "--min-patterns-per-cell",
        default=1,
        type=int,
        help="Minimum valid patterns required per group/subid/hemisphere cell. Default: 1.",
    )
    parser.add_argument("--no-plots", action="store_true")
    return parser.parse_args()


def aggregate_subjects(df: pd.DataFrame, metric: str, subject_agg: str, min_patterns: int) -> pd.DataFrame:
    work = df.copy()
    work[metric] = pd.to_numeric(work[metric], errors="coerce")
    grouped = work.groupby(["group", "subid", "hemisphere"], as_index=False)
    if subject_agg == "median":
        out = grouped.agg(
            beta=("msd_beta", "median"),
            beta_mean=("msd_beta", "mean"),
            beta_median=("msd_beta", "median"),
            selected_window_r2_mean=("r2", "mean"),
            n_patterns=("msd_beta", "count"),
            mean_duration=("duration", "mean"),
        )
    else:
        out = grouped.agg(
            beta=("msd_beta", "mean"),
            beta_mean=("msd_beta", "mean"),
            beta_median=("msd_beta", "median"),
            selected_window_r2_mean=("r2", "mean"),
            n_patterns=("msd_beta", "count"),
            mean_duration=("duration", "mean"),
        )
    out = out[out["n_patterns"] >= min_patterns].copy()
    out["subid"] = out["subid"].astype(str)
    out["group"] = out["group"].astype(str)
    out["hemisphere"] = out["hemisphere"].astype(str)
    return out


def plot_summary(per_subject: pd.DataFrame, out_dir: Path, cfg: Config, save_plots: bool) -> None:
    if not save_plots or per_subject.empty:
        return
    sns.set_theme(style="whitegrid", context="talk")
    hemispheres = [h for h in ["left", "right"] if h in set(per_subject["hemisphere"])]
    for hemi in hemispheres:
        tidy = per_subject[per_subject["hemisphere"] == hemi][["subid", "group", "beta"]].copy()
        plot_paired_violin(
            tidy,
            "beta",
            hemi,
            "MSD beta paired",
            out_dir / f"paired_msd_beta_{hemi}.png",
            cfg,
        )

    fig, ax = plt.subplots(figsize=(7, 5))
    sns.pointplot(
        data=per_subject,
        x="hemisphere",
        y="beta",
        hue="group",
        hue_order=[cfg.group_pcb, cfg.group_drug],
        errorbar="se",
        dodge=0.25,
        markers="o",
        capsize=0.1,
        ax=ax,
    )
    ax.set_title("MSD beta")
    ax.set_xlabel("Hemisphere")
    ax.set_ylabel("Subject-level beta")
    fig.tight_layout()
    fig.savefig(out_dir / "msd_beta_group_x_hemisphere.png", dpi=300)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 5))
    sns.violinplot(
        data=per_subject,
        x="hemisphere",
        y="beta",
        hue="group",
        hue_order=[cfg.group_pcb, cfg.group_drug],
        cut=0,
        split=False,
        ax=ax,
    )
    ax.set_title("MSD beta distribution")
    ax.set_xlabel("Hemisphere")
    ax.set_ylabel("Subject-level beta")
    fig.tight_layout()
    fig.savefig(out_dir / "msd_beta_violin_by_group_hemisphere.png", dpi=300)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    per_pattern = pd.read_csv(args.per_pattern)
    required = {"group", "subid", "hemisphere", args.metric, "pattern_id"}
    missing = required - set(per_pattern.columns)
    if missing:
        raise ValueError(f"{args.per_pattern} is missing columns: {sorted(missing)}")

    if args.metric != "msd_beta":
        per_pattern = per_pattern.rename(columns={args.metric: "msd_beta"})
    per_subject = aggregate_subjects(
        per_pattern,
        metric="msd_beta",
        subject_agg=args.subject_agg,
        min_patterns=args.min_patterns_per_cell,
    )
    if per_subject.empty:
        raise RuntimeError("No subject-level rows remain after aggregation/filtering.")

    cfg = Config()
    cfg.group_drug = args.group_drug
    cfg.group_pcb = args.group_pcb
    cfg.save_plots = not args.no_plots
    cfg.results_prefix = args.out_dir.name

    write_table(per_subject, args.out_dir / "per_subject_msd_beta.csv")
    summary = build_group_summary_df(
        per_subject,
        metric_cols=["beta", "beta_mean", "beta_median", "selected_window_r2_mean", "n_patterns", "mean_duration"],
        cfg=cfg,
        group_col="group",
        pair_col="subid",
        within_col="hemisphere",
    )
    write_table(summary, args.out_dir / "msd_beta_group_summary.csv")
    plot_summary(per_subject, args.out_dir, cfg, save_plots=not args.no_plots)

    metadata = {
        "per_pattern": str(args.per_pattern),
        "group_drug": args.group_drug,
        "group_pcb": args.group_pcb,
        "subject_agg": args.subject_agg,
        "min_patterns_per_cell": int(args.min_patterns_per_cell),
        "n_pattern_rows": int(len(per_pattern)),
        "n_subject_rows": int(len(per_subject)),
        "n_subjects": int(per_subject["subid"].nunique()),
    }
    (args.out_dir / "run_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"Wrote MSD beta group analysis to: {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
